---
- name: Install dependencies
  apt:
    name:
      - curl
    state: present
    update_cache: true
  become: true

- name: Download Vector binary
  get_url:
    url: "https://packages.timber.io/vector/latest/vector-amd64.tar.gz"
    dest: /tmp/vector.tar.gz
  become: true

- name: Extract Vector
  unarchive:
    src: /tmp/vector.tar.gz
    dest: /usr/local/bin/
    remote_src: yes
  become: true

- name: Create Vector config directory
  file:
    path: /etc/vector
    state: directory
  become: true

- name: Deploy config
  template:
    src: vector.toml.j2
    dest: /etc/vector/vector.toml
  become: true

- name: Create systemd service for Vector
  copy:
    dest: /etc/systemd/system/vector.service
    content: |
      [Unit]
      Description=Vector
      After=network.target

      [Service]
      ExecStart=/usr/local/bin/vector
      Restart=always

      [Install]
      WantedBy=multi-user.target
  become: true

- name: Reload systemd
  systemd:
    daemon_reload: true
  become: true

- name: Enable and start Vector
  systemd:
    name: vector
    state: started
    enabled: true
  become: true
