---
- name: Add Vector repository
  shell: |
    curl -1sLf 'https://repositories.timber.io/public/vector/cfg/setup/bash.deb.sh' | bash
  become: true

- name: Install Vector
  apt:
    name: vector
    state: present
    update_cache: true
  become: true

- name: Deploy config
  template:
    src: vector.toml.j2
    dest: /etc/vector/vector.toml
  notify: restart vector
  become: true

- name: Enable Vector
  service:
    name: vector
    state: started
    enabled: true
  become: true
